### ISSUE TITLE
Trying to modify the College Cards

### ISSUE THREAD

**Issue by PHI34Halladay** [vasqued2/ha-teamtracker-card#72] opened 2023-12-08 13:11 UTC
Hi,

I thought I'll install a custom scoreboard view for the leagues I'm following (NFL, MLB, NHL, NBA and College).

Unfortunately there are about 5000 College Basketball on a weekend and the board gets too long. So I thought, it would be cool to only have ranked teams to show up on the NCAAB tab.

However I'm not completely getting it done the way I want to have it:

The first idea was to only show ranked teams by adding the first yellow part in the screenshot, which works perfectly, but of course it will only show the 24th ranked team. All non-ranked teams have "null" in the column, where it says "team_rank". Any tips on a workaround?
![image](https://github.com/vasqued2/ha-teamtracker-card/assets/46962608/636ab4f0-a09c-4139-99d2-6aafe0c220d3)

The second idea is to exclude the "null"-ranked teams (see below), which is also not working.
![image](https://github.com/vasqued2/ha-teamtracker-card/assets/46962608/87607f68-98db-487c-bca0-3e8605f3221d)

Oh by the way: Excluding "FINAL" games (through "clock" in the first screenshot) works tho.

Would be cool to hear frome somebody with more knowledge than I have :)

**Comment by vasqued2** [comment] 2023-12-15 21:25
I haven't used it but auto-entities has the ability to sort based on attribute.  It seems like you should be able to sort based on team_rank.  If you go to the [auto-entities](https://github.com/thomasloven/lovelace-auto-entities?tab=readme-ov-file#sorting-entities) page you can see what the options are and how to use them.

You should be able to filter to only include ones where team_rank is not null.  It looks like you pasted a test for 24 for each example instead of your test for not null so not sure what you did wrong but it should be possible.

Let me know if you this is enough to get you started or if you are still having problems.

**Comment by vasqued2** [comment] 2023-12-22 14:24
Closing as confirmed this can be solved as described above.

**Closed by vasqued2** 2023-12-22 14:24 UTC
